config/routes.rb
 Rails.application.routes.draw do |map|
	match "search", :controller => 'jrank/search', :action => "index", :as => "jrank_search"
 end

app/controllers/jrank/jrank_controller.rb
module Jrank
  class SearchController < ApplicationController

  	unloadable

	def index
	end
	
	def show
	  @jrank = JRank::Search.new.find(@query, @start ||= 0, @limit ||= 10)
	end
  end
end

app/controllers/jrank/search_controller.rb
class Jrank::SearchController < ApplicationController

	unloadable

	def index
		if !params[:query].blank?
			@jrank = Jrank::Search.new.find(params[:query], params[:start] ||= "0", params[:limit] ||= "10")
		end
	end
end

app/helpers/jrank/search_helper.rb
module Jrank::SearchHelper
	def html_render(str)
		str.gsub('&amp;', '&').gsub('&lt;', '<').gsub('&gt;', '>').html_safe
	end
end

app/views/jrank/search/_form.html.erb
<form method="get" action="<%= jrank_search_path %>" class="jrank_form">
	<%= field_set_tag "Search Form" do %>
		<%= label_tag "query", "Search" %>
		<%= search_field_tag "query" %>
		<input type="submit" value="Submit" />
	<% end %>
</form>

app/views/jrank/search/_paging.html.erb
<% if total_pages.to_i > 1 %>
	<ul class="jrank_paging">
	<% pages.each do |page| %>
		<li>
			<% unless page.number == current_page or html_render(page.number) == "&hellip;" %>
				<%= link_to (page.number.to_i+1), params.merge( :start => page.start ) %>
			<% else %>
				<span>
					<%= page.number.to_i+1 if html_render(page.number) != "&hellip;" && page.number == current_page%>
					<%= html_render(page.number) if html_render(page.number) == "&hellip;" %>
				</span>
			<% end %>
		</li>
	<% end %>
	</ul>
<% end %>

app/views/jrank/search/_result.html.erb
<li>
	<h3><%= html_render(entry.title) %></h3>
	<p><%= html_render(entry.content) %></p>
	<p><%= link_to entry.url, entry.url %></p>
</li>

app/views/jrank/search/_results.html.erb
	<ul class="jrank_entries">
		<% if total > "0" %>
			<% entries.each do |entry| %>
				<%= render "result", :entry => entry %>
			<% end %>
		<% else %>
			<li>No results found for <%= query %></li>
		<% end %>
	</ul>

app/views/jrank/search/index.html.erb
<h1>JRank Site Search</h1>

<%= render "form" %>

<% unless @jrank.nil? %>
	<h2>Results for "<%= @jrank.meta.query %>"</h2>
	<%= render "results", :entries => @jrank.entries, :total => @jrank.meta.total, :query => @jrank.meta.query %>

	<%= render "paging", :pages => @jrank.pages, :current_page => @jrank.meta.current_page, :total_pages => @jrank.meta.total_pages %>
<% end %>
<p>
	<a style="display:inline-block" href="http://www.jrank.org/">
		<img alt="Site Search" src="http://www.jrank.org/images/jrank_88_31-fs8.png" title="JRank Site Search">
	</a>
</p>

app/views/jranksearch/show.html.erb
<h1>JRank Site Search Results</h1>
<p>Form goes here</p>

<% @jrank.entities.each do |entity| %>
	<%= render "result", :entity => entity  %>
<% end %>

<%= render "paging", :pages => @jrank.pages %>